import os
import sys
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'iot_portal.settings')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
django.setup()

from catalogue.models import Dataset, Domain, User

user, _ = User.objects.get_or_create(username='demo', defaults={'email': 'demo@example.com'})

datasets = [
    {
        'title': 'Borehole Pump CO2 & Humidity (Equipment Room)',
        'description': 'Environmental conditions in pump-house equipment rooms; supports predictive-maintenance research on control electronics.',
        'domain_name': 'Water',
        'sensor_type': 'Humidity',
        'iuc_project_code': 'IUC-WATER',
        'output_format': 'CSV',
        'location': 'Mbarara, Uganda',
        'update_frequency': 'Every 5 min',
        'start_date': '2024-12-01',
        'end_date': None,
        'units_of_measurement': 'ppm, %RH',
        'quality_score': 3.2,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Engineering',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 41,
        'researcher': user,
    },
    {
        'title': 'Urban Heat & Acoustic Comfort — Old Town Zanzibar',
        'description': 'Joint heat-stress and sound-level mapping along pedestrian streets, supporting heritage-conscious urban-design proposals.',
        'domain_name': 'Heritage',
        'sensor_type': 'Sound',
        'iuc_project_code': 'IUC-HERITAGE',
        'output_format': 'CSV',
        'location': 'Stone Town, Zanzibar',
        'update_frequency': 'Every 30 s',
        'start_date': '2025-02-01',
        'end_date': '2025-09-30',
        'units_of_measurement': '°C, dB',
        'quality_score': 4.0,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Architecture',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 76,
        'researcher': user,
    },
    {
        'title': 'Daylight Harvesting — Library Reading Rooms',
        'description': 'Lux and occupancy sensors in three library reading rooms to evaluate daylight-linked LED dimming strategies.',
        'domain_name': 'Energy',
        'sensor_type': 'Light',
        'iuc_project_code': 'IUC-ENERGY',
        'output_format': 'CSV',
        'location': 'ARU Library',
        'update_frequency': 'Every 1 min',
        'start_date': '2025-03-01',
        'end_date': None,
        'units_of_measurement': 'lux',
        'quality_score': 3.4,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Engineering',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 58,
        'researcher': user,
    },
    {
        'title': 'Smart-Meter Energy Profiles — Campus Residences',
        'description': 'Sub-metered electricity consumption at outlet level across 12 student residences to study peak demand and appliance signatures.',
        'domain_name': 'Energy',
        'sensor_type': 'Energy',
        'iuc_project_code': 'IUC-ENERGY',
        'output_format': 'JSON',
        'location': 'ARU Main Campus',
        'update_frequency': 'Every 15 s',
        'start_date': '2025-01-01',
        'end_date': None,
        'units_of_measurement': 'kWh',
        'quality_score': 3.9,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Engineering',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 154,
        'researcher': user,
    },
    {
        'title': 'Social Housing Indoor Air Quality — Mwanza',
        'description': 'Continuous PM2.5, PM10, CO2 and humidity logging across 60 low-income dwellings, paired with cooking-fuel surveys.',
        'domain_name': 'Housing',
        'sensor_type': 'Air Quality',
        'iuc_project_code': 'IUC-HOUSING',
        'output_format': 'CSV',
        'location': 'Mwanza, Tanzania',
        'update_frequency': 'Every 1 min',
        'start_date': '2024-09-01',
        'end_date': None,
        'units_of_measurement': 'µg/m³, ppm, %RH',
        'quality_score': 4.2,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Public Health',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 198,
        'researcher': user,
    },
    {
        'title': 'Kampala BRT Corridor — Bus Dwell-Time & Passenger Load',
        'description': 'GPS + occupancy sensors deployed across 42 buses on the pilot Bus Rapid Transit corridor capturing dwell time at stops, passenger count proxies and route adherence over 14 months.',
        'domain_name': 'Transport',
        'sensor_type': 'Motion',
        'iuc_project_code': 'IUC-MOBILITY',
        'output_format': 'CSV',
        'location': 'Kampala, Uganda',
        'update_frequency': 'Every 10 s',
        'start_date': '2024-03-01',
        'end_date': '2025-05-31',
        'units_of_measurement': 's, passengers, lat/long',
        'quality_score': 4.6,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Transport',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 312,
        'researcher': user,
    },
    {
        'title': 'Roadside PM2.5 Network — Dar es Salaam',
        'description': 'Low-cost particulate matter sensors at 28 roadside locations with reference-grade co-location calibration.',
        'domain_name': 'Air Quality',
        'sensor_type': 'Air Quality',
        'iuc_project_code': 'IUC-AIR',
        'output_format': 'CSV',
        'location': 'Dar es Salaam, Tanzania',
        'update_frequency': 'Every 1 min',
        'start_date': '2024-02-01',
        'end_date': '2025-03-31',
        'units_of_measurement': 'µg/m³',
        'quality_score': 3.6,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Environmental Science',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 405,
        'researcher': user,
    },
    {
        'title': 'Clinic Cold-Chain Temperature Logs',
        'description': 'Pharmaceutical-grade temperature monitoring of vaccine fridges across 18 rural clinics; includes power-outage event markers.',
        'domain_name': 'Health',
        'sensor_type': 'Temperature',
        'iuc_project_code': 'IUC-HEALTH',
        'output_format': 'CSV',
        'location': 'Western Region, Uganda',
        'update_frequency': 'Every 2 min',
        'start_date': '2024-04-01',
        'end_date': None,
        'units_of_measurement': '°C',
        'quality_score': 4.7,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Public Health',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 268,
        'researcher': user,
    },
    {
        'title': 'Lake Victoria Nearshore Water Quality Buoys',
        'description': 'Six tethered buoys logging dissolved oxygen, turbidity, pH and surface temperature; supports algal bloom early warning research.',
        'domain_name': 'Water',
        'sensor_type': 'Water Quality',
        'iuc_project_code': 'IUC-WATER',
        'output_format': 'CSV',
        'location': 'Entebbe, Uganda',
        'update_frequency': 'Every 5 min',
        'start_date': '2024-06-01',
        'end_date': None,
        'units_of_measurement': 'mg/L, NTU, pH, °C',
        'quality_score': 4.4,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Fisheries',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 221,
        'researcher': user,
    },
    {
        'title': 'Matatu Fleet Vibration & Route Roughness',
        'description': 'Three-axis accelerometers on 30 minibus taxis, building a crowdsourced road-roughness index for urban planners.',
        'domain_name': 'Transport',
        'sensor_type': 'Vibration',
        'iuc_project_code': 'IUC-MOBILITY',
        'output_format': 'CSV',
        'location': 'Nairobi, Kenya',
        'update_frequency': 'Every 100 ms',
        'start_date': '2024-08-01',
        'end_date': None,
        'units_of_measurement': 'm/s²',
        'quality_score': 3.8,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Transport',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 189,
        'researcher': user,
    },
    {
        'title': 'Fort Jesus Microclimate & Structural Vibration',
        'description': 'Heritage-site monitoring: temperature, humidity and low-frequency vibration sensors embedded in coral-stone walls to track conservation risk.',
        'domain_name': 'Heritage',
        'sensor_type': 'Vibration',
        'iuc_project_code': 'IUC-HERITAGE',
        'output_format': 'CSV',
        'location': 'Mombasa, Kenya',
        'update_frequency': 'Every 30 s',
        'start_date': '2023-11-01',
        'end_date': None,
        'units_of_measurement': '°C, %RH, m/s²',
        'quality_score': 4.8,
        'license': 'CC BY 4.0',
        'download_link': '',
        'department': 'Heritage',
        'data_file': None,
        'doi': '',
        'status': 'live',
        'download_count': 87,
        'researcher': user,
    },
]

for d in datasets:
    domain = Domain.objects.get(name=d['domain_name'])
    Dataset.objects.create(
        title=d['title'],
        description=d['description'],
        researcher=d['researcher'],
        domain=domain,
        sensor_type=d['sensor_type'],
        iuc_project_code=d['iuc_project_code'],
        output_format=d['output_format'],
        location=d['location'],
        update_frequency=d['update_frequency'],
        start_date=d['start_date'],
        end_date=d['end_date'],
        units_of_measurement=d['units_of_measurement'],
        quality_score=d['quality_score'],
        license=d['license'],
        download_link=d['download_link'],
        department=d['department'],
        data_file=d['data_file'],
        doi=d['doi'],
        status=d['status'],
        download_count=d['download_count'],
    )

print(f'Created {len(datasets)} datasets')
