# Generated by Django 6.0.6 on 2026-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_add_profile_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_zone_auto_detected',
            field=models.BooleanField(default=False),
        ),
    ]
