# Generated by Django 6.0.6 on 2026-07-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_add_profile_time_zone_auto_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
